version: '3.7'
services:
  frontend_local:
    # build: ./frontend
    container_name: nextPrj
    image: frontend_local
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app
    restart: always
    ipc: host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Seoul
    command: tail -F /dev/null
    # command: npm start
